### ISSUE TITLE
The range of BERT-disk layers 

### ISSUE THREAD

**Issue by nuradilK** [john-hewitt/structural-probes#11]
Hi, I have been trying to make a structural probe for BERT-large's 16th layer. However, I am facing a problem that the valid range of layers is (0-2). I have no idea why the range is not correct. 

P.S Could you please check my configs?

```
run_experiment.py:238: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_args= yaml.load(open(cli_args.experiment_config))
Constructing new results directory at /Users/nurikkozahmet/Desktop/structural-probes/example/results/BERT-disk-parse-distance-2020-4-2-23-53-17-192645/
Loading BERT Pretrained Embeddings from /Users/nurikkozahmet/Desktop/structural-probes/example/data/en_ewt-ud-sample/en_ewt-ud-train.elmo-layers.hdf5; using layer 15
The pre-trained model you are loading is a cased model but you have not set `do_lower_case` to False. We are setting `do_lower_case=False` for you but you may want to check this behavior.
Using BERT-large-cased tokenizer to align embeddings with PTB tokens
[aligning embeddings]:   0%|                                                                                           | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_experiment.py", line 242, in <module>
    execute_experiment(yaml_args, train_probe=cli_args.train_probe, report_results=cli_args.report_results)
  File "run_experiment.py", line 170, in execute_experiment
    expt_dataset = dataset_class(args, task)
  File "/Users/nurikkozahmet/Desktop/structural-probes/structural-probes/data.py", line 34, in __init__
    self.train_obs, self.dev_obs, self.test_obs = self.read_from_disk()
  File "/Users/nurikkozahmet/Desktop/structural-probes/structural-probes/data.py", line 65, in read_from_disk
    train_observations = self.optionally_add_embeddings(train_observations, train_embeddings_path)
  File "/Users/nurikkozahmet/Desktop/structural-probes/structural-probes/data.py", line 407, in optionally_add_embeddings
    embeddings = self.generate_subword_embeddings_from_hdf5(observations, pretrained_embeddings_path, layer_index)
  File "/Users/nurikkozahmet/Desktop/structural-probes/structural-probes/data.py", line 393, in generate_subword_embeddings_from_hdf5
    single_layer_features = feature_stack[elmo_layer]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 466, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 486, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (15) out of range (0-2)
```

[configs.txt](https://github.com/john-hewitt/structural-probes/files/4422755/configs.txt)

**Comment by nuradilK** [comment]
Also, I guess that the hdf5 file containing embeddings has some problems. I think that the following code from data.py will always return AssertionError.

```
for index in tqdm(sorted([int(x) for x in indices]), desc='[aligning embeddings]'):
      observation = observations[index]
      feature_stack = hf[str(index)]
      single_layer_features = feature_stack[elmo_layer]
      tokenized_sent = subword_tokenizer.wordpiece_tokenizer.tokenize('[CLS] ' + ' '.join(observation.sentence) + ' [SEP]')
      untokenized_sent = observation.sentence
      untok_tok_mapping = self.match_tokenized_to_untokenized(tokenized_sent, untokenized_sent)
      assert single_layer_features.shape[0] == len(tokenized_sent)
      single_layer_features = torch.tensor([np.mean(single_layer_features[untok_tok_mapping[i][0]:untok_tok_mapping[i][-1]+1,:], axis=0) for i in range(len(untokenized_sent))])
      assert single_layer_features.shape[0] == len(observation.sentence)
      single_layer_features_list.append(single_layer_features)
```

**Comment by john-hewitt** [comment]
Hi! In your config, it looks like you're using ELMo embeddings, if you're using the sample embeddings provided by `download_example.sh`:

```
train_path: en_ewt-ud-train.elmo-layers.hdf5
dev_path: en_ewt-ud-dev.elmo-layers.hdf5
test_path: en_ewt-ud-test.elmo-layers.hdf5
```

which means you cannot use BERT-disk as the model. Further, ELMo only has 3 layers, which is why 0-2 are the only valid layers.

The assertion error you're getting is because you're running the BERT tokenizer and trying to align the embeddings to a BERT-tokenized sequence. This is required for BERT models due to the subword embeddings of BERT, but ELMo provides a single embedding per word, so the alignment fails.

If you want to use BERT, you can use the `convert_raw_to_bert.py` script to write BERT embeddings to disk for some text file.

**Comment by nuradilK** [comment]
Hi! Thanks for the help, I have solved the problem. However, I have some questions about the structural probe matrix B. I wanted to visualize embeddings of sentences after applying the probe matrix B by making a PCA projection. Nevertheless, I could not find the matrix B in this repository. Am I right that you make predictions of depth and pair-distance without using the matrix B?

**Comment by john-hewitt** [comment]
Glad to hear you solved the problem!

The probe matrix B is given by the attribute `proj` of the `TwoWordPSDProbe` class (for the distance probe) and the attribute `proj` of the OneWordPSDProbe` class (for the depth probe.) After training the probe, this parameter matrix is what you're looking for.

When running `download_example.sh`, the files `bertlarge16-distance-probe.params` and `bertlarge16-depth-probe.params` are both B matrices trained for BERT on the Penn Treebank, and used via `run_demo.py`.

**Comment by john-hewitt** [comment]
Closing; feel free to re-open if you have further questions.
